---
collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: community.crypto
  - name: community.general
  - name: community.libvirt
  - name: containers.podman

  - name: infra.osbuild
    source: https://github.com/redhat-cop/infra.osbuild.git
    type: git

...
