---
- name: Configure FDO node
  hosts: fdo-node
  gather_facts: true
  become: true

  vars_files:
    - vars/demo_vars.yml
    - vars/vault.yml

  tasks:
    - name: Subscribe FDO node
      community.general.redhat_subscription:
        state: present
        org_id: '{{ vault_rhsm_organization }}'
        activationkey: '{{ vault_rhsm_activation_key }}'

    - name: Update FDO node packages
      # noqa package-latest
      ansible.builtin.dnf:
        name: '*'
        state: latest

    - name: Install additional packages
      ansible.builtin.dnf:
        name:
          - bash-completion
          - jq
        state: present

    - name: Install container-tools for FDO node on RHEL 9
      ansible.builtin.dnf:
        name: container-tools
        state: present
      when: ansible_distribution_major_version == '9'

    - name: Add user to weldr group
      ansible.builtin.user:
        name: '{{ ansible_env.SUDO_USER }}'
        groups: weldr

    - name: Run osbuild setup
      ansible.builtin.import_role:
        name: infra.osbuild.setup_server

...
# vim: ft=yaml.ansible
