---
- name: Prep FDO node for building images
  hosts: fdo-node
  gather_facts: true
  become: false

  vars_files:
    - vars/demo_vars.yml

  tasks:
    - name: Ensure $HOME/.ssh exists
      ansible.builtin.file:
        path: '{{ ansible_user_dir }}/.ssh'
        state: directory
        owner: '{{ ansible_user_id }}'
        group: '{{ ansible_user_id }}'
        mode: 0700

    - name: Create SSH key for edge node user
      community.crypto.openssh_keypair:
        path: '{{ ansible_user_dir }}/.ssh/id_{{ demo_edge_node_user }}'
        type: rsa
        size: 4096
        comment: 'Edge node key'
        owner: '{{ ansible_user_id }}'
        group: '{{ ansible_user_id }}'
        mode: 0600

    - name: Grab edge node user SSH public key for image blueprint
      ansible.builtin.slurp:
        src: '{{ ansible_user_dir }}/.ssh/id_{{ demo_edge_node_user }}.pub'
      register: _edge_node_pubkey

    - name: Create edge node image blueprint
      infra.osbuild.create_blueprint:
        name: '{{ demo_edge_blueprint_name }}'
        dest: '/tmp/edge-blueprint.toml'
        packages: '{{ demo_edge_node_packages[ansible_distribution_major_version] +
                      demo_edge_node_kiosk_packages[ansible_distribution_major_version] }}'
        customizations:
          user:
            name: '{{ demo_edge_node_user }}'
            description: 'default edge user'
            password: '{{ demo_edge_node_password | password_hash }}'
            key: '{{ _edge_node_pubkey.content | b64decode | trim }}'
            home: '/home/{{ demo_edge_node_user }}/'
            shell: '/usr/bin/bash'
            groups:
              - 'wheel'

    - name: Create installer image blueprint
      infra.osbuild.create_blueprint:
        name: '{{ demo_installer_blueprint_name }}'
        dest: '/tmp/simplified-installer.toml'
        customizations:
          installation_device: '/dev/vda'
          fdo:
            manufacturing_server_url: 'http://{{ hostvars["fdo-node"].ansible_default_ipv4.address }}:8080'
            diun_pub_key_insecure: 'true'

...
# vim: ft=yaml.ansible
