---
- name: Build rpm-ostree image for edge node
  hosts: fdo-node
  gather_facts: true
  become: false

  vars_files:
    vars/demo_vars.yml

  tasks:
    - name: Build edge node image
      tags: edge-image
      block:
        - name: Push edge node blueprint
          infra.osbuild.push_blueprint:
            src: '{{ demo_composer_artifact_dir }}/edge-blueprint.toml'

        - name: Start edge node compose
          infra.osbuild.start_compose:
            blueprint: '{{ demo_edge_blueprint_name }}'
            compose_type: edge-container
          register: _compose

        - name: Wait up to 15 minutes for edge node compose to complete
          infra.osbuild.wait_compose:
            compose_id: '{{ _compose.result.build_id }}'
            timeout: 900

        - name: Export edge node compose artifact
          infra.osbuild.export_compose:
            compose_id: '{{ _compose.result.build_id }}'
            dest: '{{ demo_composer_artifact_dir }}/edge-{{ _compose.result.build_id }}-container.tar'

        - name: Copy edge container image to local image cache
          # noqa no-changed-when
          ansible.builtin.command: >
            skopeo copy
                oci-archive:edge-{{ _compose.result.build_id }}-container.tar
                containers-storage:localhost/rfe-mirror:latest
          args:
            chdir: '{{ demo_composer_artifact_dir }}'
      # end block
      always:
        - name: Delete edge node compose artifacts
          when: demo_delete_composes | bool
          block:
            # TODO switch to infra.osbuild when feature is implemented
            # (and again below)
            - name: Delete edge node compose
              # noqa no-changed-when
              ansible.builtin.command: >
                composer-cli compose delete {{ _compose.result.build_id }}

            - name: Delete edge node compose image
              ansible.builtin.file:
                path: '{{ demo_composer_artifact_dir }}/edge-{{ _compose.result.build_id }}-container.tar'
                state: absent

    - name: Simplified installer firewall operations
      tags: edge-installer
      become: true
      block:
        - name: See if firewalld is installed
          ansible.builtin.stat:
            path: /usr/sbin/firewalld
          register: _firewalld_stat

        - name: Open FDO ports on host firewall
          ansible.posix.firewalld:
            port: '8000/tcp'
            state: enabled
            zone: '{{ "libvirt" if demo_type == "fdo-hosted" else "public" }}'
            immediate: true
            permanent: true
          when: _firewalld_stat.stat.exists

    - name: Build simplified installer image
      tags: edge-installer
      block:
        - name: Run edge node mirror container
          containers.podman.podman_container:
            name: rfe-mirror
            image: localhost/rfe-mirror
            state: started
            auto_remove: true
            publish:
              - '8000:8080'

        - name: Push simplified installer blueprint
          infra.osbuild.push_blueprint:
            src: '{{ demo_composer_artifact_dir }}/simplified-installer.toml'

        - name: Start simplified installer compose
          infra.osbuild.start_compose:
            blueprint: '{{ demo_installer_blueprint_name }}'
            compose_type: edge-simplified-installer
            ostree_url: http://localhost:8000/repo/
          register: _compose

        - name: Wait up to 15 minutes for simplified installer compose to complete
          infra.osbuild.wait_compose:
            compose_id: '{{ _compose.result.build_id }}'
            timeout: 900

        - name: Export simplified installer compose artifact
          infra.osbuild.export_compose:
            compose_id: '{{ _compose.result.build_id }}'
            dest: '{{ demo_composer_artifact_dir }}/installer-{{ _compose.result.build_id }}.iso'

        # could copy/delete but this is atomic and much faster than a copy.
        # not using 'creates' for idempotency so the target gets overwritten
        # with a new image when created.
        - name: Rename simplified installer image
          ansible.builtin.command: >
            mv -f installer-{{ _compose.result.build_id }}.iso simplified-installer.iso
          args:
            chdir: '{{ demo_composer_artifact_dir }}'
            removes: installer-{{ _compose.result.build_id }}.iso
      # end block
      always:
        - name: Delete simplified installer compose
          # noqa no-changed-when
          ansible.builtin.command: >
            composer-cli compose delete {{ _compose.result.build_id }}
          when: demo_delete_composes | bool

        - name: Remove edge node mirror container
          containers.podman.podman_container:
            name: rfe-mirror
            state: stopped

...
# vim: ft=yaml.ansible
