---
- name: Build ostree images
  ansible.builtin.import_playbook: 07-build-ostree-image.yml
- name: Create edge node VM
  ansible.builtin.import_playbook: 08-create-edge-node-vm.yml
  when: demo_type == 'fdo-hosted'
- name: Install reverse proxy for demo webapp access
  ansible.builtin.import_playbook: 09-install-haproxy.yml
  when: demo_type == 'fdo-hosted'

...
# vim: ft=yaml.ansible
